# encoding: UTF-8

defaults: &defaults
  host: localhost
  port: 6379
  db: 2
  username: username
  password: cxm
  #expires_in: 28800

  namespace: qingniu-micro-measurement-dev

development: &development
  <<: *defaults

test:
  <<: *development

production:
  #host: s1-facloud.servers.atyun.com.cn
  host: 127.0.0.1
  port: 26123
  db: 2
  username: username
  password: 8Eh5dO9tHnOfI0
  namespace: yolanda-pms-prod
