# encoding: UTF-8

defaults: &defaults
  domain: 'http://xwk.free.ngrok.cc'
  token: 'YOLSRM6H9uKCNs5efAga'
  encodingAesKey: 'cSBK6vICUbTpU77quFRGXWGMp2GDGmd9k1rORevVZRh'
  corpId: 'wx91c5262f3c33a727'
  secret: 'cb10094484b3c80726cc1973e1168b31'

development: &development
  <<: *defaults

test:
  <<: *development

production:
  domain: 'http://srm.yolanda.hk'
  token: 'YOLSRM6H9uKCNs5efAga'
  encodingAesKey: 'cSBK6vICUbTpU77quFRGXWGMp2GDGmd9k1rORevVZRh'
  corpId: 'wx91c5262f3c33a727'
  secret: 'cb10094484b3c80726cc1973e1168b31'

